# required configuration options
name: Fusion
version: 2024.12.1
slug: ha_fusion
description: 一个现代化、易用且高性能的 Home Assistant 自定义仪表盘
arch:
  - aarch64
  - amd64
  - armv7

# disable the docker default system init
init: false

# homepage of the add-on
url: https://github.com/symi-daguo/addon-ha-fusion

# icon for the menu panel integration
panel_icon: mdi:atom

# allow non-administration users
panel_admin: false

# security profile
apparmor: true

# ingress feature for the add-on
ingress: true
ingress_stream: true

# enable api to get host port
hassio_api: true

# port to expose, null defaults to disabled
ports:
  8099/tcp: null

# docker hub
image: ghcr.io/symi-daguo/addon-ha-fusion-{arch}
