# required configuration options
name: Fusion
version: 2024.12.1
slug: ha_fusion
description: 一个现代化、易用且高性能的 Home Assistant 自定义仪表盘
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 5050
panel_icon: mdi:view-dashboard
init: false
map:
  - share:rw
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  ssl: bool
  certfile: str
  keyfile: str
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: Web 界面
environment:
  TZ: "Asia/Shanghai"
  HASS_URL: "http://supervisor/core"
image: "{username}/addon-ha-fusion-{arch}"
