name: "Publish"

# Trigger on push to main branch or manual dispatch
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags:
      - "20[0-9][0-9].[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version
        id: version
        run: |
          version="2024.12.0"
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target /data \
            --docker-hub ghcr.io/symi-daguo \
            --version ${{ steps.version.outputs.version }}
